name: CI/CD

on:
  push:
    branches: [ "main", "giuaky" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  unit-testing:


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.16
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.16"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f ./10.GK/web/requirements.txt ]; then pip install -r ./10.GK/web/requirements.txt; fi
    - name: Lint with flake8
      run: |
        pytest 10.GK/web/tests/app/test_main.py
