name: CI/CD

on:
  push:
    branches: [ "main", "giuaky" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  unit-testing:


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.16
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.16"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f ./10.GK/Hoang-Quoc-Doanh/web/requirements.txt ]; then pip install -r ./10.GK/Hoang-Quoc-Doanh/web/requirements.txt; fi
    - name: Lint with flake8
      run: |
        pytest 10.GK/Hoang-Quoc-Doanh/web/tests/app/test_main.py

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:doanh/be"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/doanh-be:${{  github.ref_name }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:doanh/fe"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/doanh-fe:${{  github.ref_name }}
